version: "3.8"
services:
  client-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    env_file:
      - .env.local
  client-prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "5000:5000"
    env_file:
      - .env
