name: Python CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  docker-in-linux-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Make docker command available
      uses: docker/setup-buildx-action@v3
    - name: Build the Dockerfile
      run: docker build -f Dockerfile.dev -t test-image .
    - name: Run the tests
      run: docker run test-image npm run test

  docker-in-mac-tests:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Make docker command available
      uses: docker/setup-buildx-action@v
    - name: Build the Dockerfile
      run: docker build -f Dockerfile.dev -t test-image .
    - name: Run the tests
      run: docker run test-image npm run test
