name: WebPortal CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  docker-in-linux-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Make docker command available
      uses: docker/setup-buildx-action@v3
    - name: Build the Dockerfile
      run: docker build -f Dockerfile.dev -t test-image .
    - name: Run the tests
      run: docker run test-image npm run test

  push-to-ecr-dev:
    needs: docker-in-linux-tests
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - uses: actions/checkout@v4
    - name: Make docker command available
      uses: docker/setup-buildx-action@v3
    - name: Build the Dockerfile
      run: docker build -f Dockerfile.prod -t prod-image .
    - name: Login to ECR
      id: ecr
      uses: jwalton/gh-ecr-login@v3
      with:
        access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        region: us-east-2
    - name: Push to ECR
      run: |
        docker tag prod-image ${{ steps.ecr.outputs.account }}.dkr.ecr.us-east-2.amazonaws.com/web-portal:v1
        docker push ${{ steps.ecr.outputs.account }}.dkr.ecr.us-east-2.amazonaws.com/web-portal:v1
